/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/sysinit.o
/Users/bruno/Desktop/kicks/laz-zowe/editor.o
/Users/bruno/Desktop/kicks/laz-zowe/editor.or
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/system.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/lnfodwrf.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/exeinfo.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/ctypes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/baseunix.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/dl.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/strings.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/unixtype.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/sysctl.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/fpintres.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/objpas.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/objc.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/objcbase.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/cthreads.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/cocoaint/CocoaAll.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/interfaces.o
/Applications/lazarus/lcl/units/aarch64-darwin/forms.o
/Users/bruno/Desktop/kicks/laz-zowe/uMain.o
/Users/bruno/Desktop/kicks/laz-zowe/uZoweOps.o
/Users/bruno/Desktop/kicks/laz-zowe/uJobsForm.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/unix.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/initc.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/cocoaint/DefinedClassesFoundation.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/cocoaint/DefinedClassesCoreImage.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/cocoaint/DefinedClassesQuartzCore.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/cocoaint/DefinedClassesCoreData.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/cocoaint/DefinedClassesAppKit.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/univint/MacOSAll.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/macpas.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/blockrtl.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/univint/MacTypes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/univint/CoreAudioTypes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/math.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/sysutils.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/errors.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/sysconst.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/unixutil.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/cwstring.o
/Applications/lazarus/lcl/units/aarch64-darwin/interfacebase.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsfactory.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/dynlibs.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/unixcp.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/types.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/classes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpimage.o
/Applications/lazarus/lcl/units/aarch64-darwin/lclproc.o
/Applications/lazarus/lcl/units/aarch64-darwin/lcltype.o
/Applications/lazarus/lcl/units/aarch64-darwin/lmessages.o
/Applications/lazarus/lcl/units/aarch64-darwin/lclplatformdef.o
/Applications/lazarus/lcl/units/aarch64-darwin/intfgraphics.o
/Applications/lazarus/lcl/units/aarch64-darwin/themes.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsreferences.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazutf8.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/integerlist.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazutilities.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazloggerbase.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/graphtype.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/graphmath.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazversion.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/typinfo.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/rtlconsts.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/avl_tree.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazfileutils.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazmethodlist.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazutf16.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/laztracer.o
/Applications/lazarus/lcl/units/aarch64-darwin/lclstrconsts.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazutilsstrconsts.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/fpcadds.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-objpas/strutils.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/translations.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-json/jsonscanner.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-json/jsonparser.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-json/fpjson.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/fileutil.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lconvencoding.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/avglvltree.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/stringhashlist.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-json/jsonreader.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-objpas/variants.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/contnrs.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-objpas/varutils.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/masks.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/dos.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/codepagescommon.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/codepagesasian.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazclasses.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazdbglog.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-objpas/system.uitypes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpreadbmp.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpwritebmp.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/bmpcomn.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpreadpng.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpwritepng.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpreadtiff.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpwritetiff.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fptiffcmn.o
/Applications/lazarus/lcl/units/aarch64-darwin/lclversion.o
/Applications/lazarus/lcl/units/aarch64-darwin/icnstypes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpimgcmn.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/pngcomn.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/zstream.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/zbase.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/gzio.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/hash/crc.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/zdeflate.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/zinflate.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/trees.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/adler.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/infblock.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/infutil.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/infcodes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/inftrees.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/paszlib/inffast.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpcolorspace.o
/Applications/lazarus/lcl/units/aarch64-darwin/graphics.o
/Applications/lazarus/lcl/units/aarch64-darwin/lclintf.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpcanvas.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpreadpnm.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpwritepnm.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpreadjpeg.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpwritejpeg.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpreadgif.o
/Applications/lazarus/lcl/units/aarch64-darwin/lresources.o
/Applications/lazarus/lcl/units/aarch64-darwin/lclrescache.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/clipping.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/jpegcomn.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jpeglib.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdapimin.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdatasrc.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdapistd.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jmorecfg.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdeferr.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jinclude.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jerror.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jmemmgr.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdmarker.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdinput.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcomapi.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jutils.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jmemnobs.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdmaster.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdcolor.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdsample.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdpostct.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jddctmgr.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdphuff.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdhuff.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdcoefct.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdmainct.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jquant1.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jquant2.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdmerge.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdct.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jidctfst.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jidctint.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jidctflt.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jidctred.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcapistd.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcapimin.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jdatadst.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcparam.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcinit.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcmarker.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcphuff.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jchuff.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcmaster.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jccolor.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcsample.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcprepct.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcdctmgr.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jccoefct.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jcmainct.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jfdctint.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jfdctfst.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/pasjpeg/jfdctflt.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazconfigstorage.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/dynqueue.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazstringutils.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/syncobjs.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/utf8process.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/lazsysutils.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/maps.o
/Applications/lazarus/lcl/units/aarch64-darwin/tmschema.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/fgl.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-process/process.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-process/pipes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/termio.o
/Applications/lazarus/lcl/units/aarch64-darwin/controls.o
/Applications/lazarus/lcl/units/aarch64-darwin/comctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/stdctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/spin.o
/Applications/lazarus/lcl/units/aarch64-darwin/dialogs.o
/Applications/lazarus/lcl/units/aarch64-darwin/extctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/buttons.o
/Applications/lazarus/lcl/units/aarch64-darwin/checklst.o
/Applications/lazarus/lcl/units/aarch64-darwin/menus.o
/Applications/lazarus/lcl/units/aarch64-darwin/calendar.o
/Applications/lazarus/lcl/units/aarch64-darwin/wslclclasses.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsdialogs.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawscommon.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsbuttons.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsextctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsforms.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsmenus.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsstdctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawscomctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsdialogs.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsspin.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawschecklst.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsdatepicker.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawslistview.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsdragimage.o
/Applications/lazarus/lcl/units/aarch64-darwin/imglist.o
/Applications/lazarus/lcl/units/aarch64-darwin/propertystorage.o
/Applications/lazarus/lcl/units/aarch64-darwin/actnlist.o
/Applications/lazarus/lcl/units/aarch64-darwin/lclclasses.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fpimgcanv.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/fppixlcanv.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/pixtools.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/ellipses.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-image/polygonfilltools.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsimglist.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsproc.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsfactory.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/rttiutils.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsmenus.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/custapp.o
/Applications/lazarus/lcl/units/aarch64-darwin/customtimer.o
/Applications/lazarus/lcl/units/aarch64-darwin/clipbrd.o
/Applications/lazarus/lcl/units/aarch64-darwin/helpintfs.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/singleinstance.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/chm/fasthtmlparser.o
/Applications/lazarus/lcl/units/aarch64-darwin/wscontrols.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsforms.o
/Applications/lazarus/lcl/units/aarch64-darwin/toolwin.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/textstrings.o
/Applications/lazarus/components/lazutils/lib/aarch64-darwin/extendedstrings.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsstdctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/popupnotifier.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsextctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/imagelistcache.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsbuttons.o
/Applications/lazarus/lcl/units/aarch64-darwin/wscomctrls.o
/Applications/lazarus/lcl/units/aarch64-darwin/wstoolwin.o
/Applications/lazarus/lcl/units/aarch64-darwin/wsspin.o
/Applications/lazarus/lcl/units/aarch64-darwin/buttonpanel.o
/Applications/lazarus/lcl/units/aarch64-darwin/dialogres.o
/Applications/lazarus/lcl/units/aarch64-darwin/taskdlgemulation.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-objpas/dateutils.o
/Applications/lazarus/lcl/units/aarch64-darwin/wschecklst.o
/Applications/lazarus/lcl/units/aarch64-darwin/wscalendar.o
/Applications/lazarus/lcl/units/aarch64-darwin/lclmessageglue.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoaint.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoaconfig.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoaprivate.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoacallback.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoautils.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoacustomcontrol.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoascrollers.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsscrollers.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoafullcontroledit.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoagdiobjects.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoacursor.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoacaret.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoa_extra.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoaconst.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoamenus.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawindows.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoawsclipboard.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoatextedits.o
/Applications/lazarus/lcl/units/aarch64-darwin/customdrawndrawers.o
/Applications/lazarus/lcl/units/aarch64-darwin/customdrawn_mac.o
/Applications/lazarus/lcl/units/aarch64-darwin/customdrawn_common.o
/Applications/lazarus/lcl/units/aarch64-darwin/comboex.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoalistcontrol.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoatables.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoabuttons.o
/Applications/lazarus/lcl/units/aarch64-darwin/graphutil.o
/Applications/lazarus/lcl/units/aarch64-darwin/lazcanvas.o
/Applications/lazarus/lcl/units/aarch64-darwin/lazregions.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoathemes.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoalistview.o
/Applications/lazarus/lcl/units/aarch64-darwin/messages.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoatoolbar.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoatabcontrols.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoastatusbar.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoadatepicker.o
/Applications/lazarus/lcl/units/aarch64-darwin/cocoa/cocoacollectionview.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedit.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedittypes.o
/Users/bruno/Desktop/kicks/laz-zowe/uSynHighlighter.o
/Users/bruno/Desktop/kicks/laz-zowe/uConfig.o
/Users/bruno/Desktop/kicks/laz-zowe/uProfileForm.o
/Users/bruno/Desktop/kicks/laz-zowe/uFindForm.o
/Users/bruno/Desktop/kicks/laz-zowe/uAllocForm.o
/Users/bruno/Desktop/kicks/laz-zowe/uDsBrowse.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/lazsynimmbase.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/lazsyncocoaimm.o
/Applications/lazarus/lcl/units/aarch64-darwin/stdactns.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditsearch.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditkeycmds.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmousecmds.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmiscprocs.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditpointclasses.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synbeautifier.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarks.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarkup.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarkuphighall.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarkupbracket.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarkupwordgroup.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarkupctrlmouselink.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarkupspecialline.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarkupselection.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmarkupspecialchar.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedittextbase.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/lazsynedittext.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedittextbuffer.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditlines.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedittexttrimmer.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedittexttabexpander.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedittextdoublewidthchars.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditfoldedview.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syngutterbase.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syngutter.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditmiscclasses.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedithighlighter.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/lazsyntextarea.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syntextdrawer.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedittextbidichars.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synguttercodefolding.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syngutterchanges.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syngutterlinenumber.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synguttermarks.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syngutterlineoverview.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-registry/registry.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/inifiles.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-registry/xmlreg.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/dom.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmlread.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmlwrite.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmlutils.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/dtdmodel.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/uriparser.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmlreader.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmltextreader.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/syneditstrconst.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/lazsyneditmousecmdstypes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/regexpr/regexpr.o
/Applications/lazarus/components/synedit/units/aarch64-darwin/cocoa/synedithighlighterfoldbase.o
